name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      # Step 3: Install backend dependencies (root)
    #   - name: Install backend dependencies
    #     run: npm install --force
    #     working-directory: .

      # # Step 4: Install frontend dependencies
      # - name: Install frontend dependencies
      #   run: npm install --force
      #   working-directory: ./frontend

      # # Step 5: Build the frontend application
      # - name: Build frontend application
      #   run: npm run build
      #   working-directory: ./frontend

      # Step 6: Setup SSH for Deployment
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H dev.zealits.com >> ~/.ssh/known_hosts

      # Step 7: Deploy to the server
      - name: Deploy to server
        if: github.ref == 'refs/heads/main'
        run: |
          ssh admin@dev.zealits.com << 'EOF'
            # Backup the .env file if it exists
            if [ -f ~/studieshq-transformation/backend/.env ]; then
              cp ~/studieshq-transformation/backend/.env ~/.env.bak
            fi

            # Use git pull if the repository exists; otherwise, clone it
            if [ -d ~/studieshq-transformation ]; then
              cd ~/studieshq-transformation
              git pull origin main
            else
              git clone https://github.com/zealits/BiddingApp.git ~/BiddingApp
              cd ~/studieshq-transformation
            fi

            # Restore the config.env file if a backup exists
            if [ -f ~/.env.bak ]; then
              mv ~/.env.bak ~/studieshq-transformation/backend/.env
            fi

            # Install backend dependencies
            cd backend
            npm install

            cd ..

            # Install frontend dependencies and build
            cd frontend
            npm install --force
            npm run build
            cd ..

            cd backend
            # Restart the application using PM2
            if pm2 list | grep -q "studieshq-transformation"; then
              echo "Restarting BiddingApp"
              pm2 restart studieshq-transformation
            else
              echo "Starting BiddingApp"
              pm2 start npm --name "studieshq-transformation" -- run dev
            fi

            # Check the status of PM2 processes
            pm2 list
          EOF